name: CI
on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu-utils
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils

      - uses: actions/checkout@v2

      - name: Build image
        run: |
          sudo ./alpine-make-vm-image \
              --image-format qcow2 \
              --image-size 800M \
              --repositories-file example/repositories \
              --packages "$(cat example/packages)" \
              --initfs-features "btrfs scsi virtio" \
              --script-chroot \
              --serial-console \
              alpine-virthardened-$(date +%Y-%m-%d).qcow2 -- ./example/configure.sh
              
      - name: Uploading artifacts
        uses: actions/upload-artifact@v2
        with:
          name: alpine-qcow2
          path: ./*.qcow2
